config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  resources :records
  root 'static_pages#home'
  
  get 'rec' => 'records#index'

end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def index
    @records = Record.all
  end
  
  def create
    @record = Record.new(record_params)
    if @record.save
      render json: @record
    else
      render json: @record.errors, status: :unprocessable_entity
    end
  end

  def destroy
    Record.find(params[:id]).destroy
    head :no_content
  end
  
  def update
    @record = Record.find(params[:id])
    if @record.update(record_params)
      render json: @record
    else
      render json: @record.erros, status: :unprocessable_entity
    end
  end
  
  private

    def record_params
      params.require(:record).permit(:title, :amount, :date)
    end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReactExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

 <pre>
      <!-- Here's some values to keep an eye on in the sample in order to understand $state and $stateParams -->
      $state = {{$state.current.name}}
      $stateParams = {{$stateParams}}
      $state full url = <%= request.original_url %>
      <!-- $state.$current is not a public api, we are using it to
           display the full url for learning purposes-->
               <%= debug(params) if Rails.env.development? %>
    </pre>

</body>
</html>

app/views/records/index.html.erb
<%= react_component 'Records', { data: @records } %>

app/views/static_pages/home.html.erb
<%= link_to "Record", records_url %>
 